### ISSUE TITLE
nim-mode compilation error during installation

### ISSUE THREAD

**Issue by Scramblejams** [reactormonk/nim-mode#16]
Installing from elpa, I get this:

    Compiling file /home/steve/.emacs.d/elpa/nim-mode-20150203.802/nim-mode-pkg.el at Tue Feb 3 21:48:51 2015
    Entering directory `/home/steve/.emacs.d/elpa/nim-mode-20150203.802/'

    Compiling file /home/steve/.emacs.d/elpa/nim-mode-20150203.802/nim-mode.el at Tue Feb 3 21:48:51 2015
    nim-mode.el:184:1:Error: Symbol's value as variable is void: nim-keywords

Running emacs 24.4.1 on Debian Jessie.

**Comment by purcell** [comment]
Yep: `flycheck` also reports this issue, so if byte-compilation is working for you, @reactormonk, it's because you're doing it inside an Emacs which already has that symbol defined.

What's happening is that `rx` expands its forms into a regexp at compile time, but the `defconst` of `nim-types` defines a runtime value. So at the time `rx` tries to use it in an expansion, its value is not available.

The fix is to instead use `rx-to-string` in those backtick expressions.

**Comment by reactormonk** [comment]
@purcell I've changed that, now I hit another error on line https://github.com/reactormonk/nim-mode/blob/master/nim-mode.el#L268 because the macro expands the rx-constituents, which are now defined at runtime. I'm not sure if it's the right path for a major mode to store static information such as builtins at runtime, I'd be fine with directly compiling them in instead.

**Comment by purcell** [comment]
It seems to work if you wrap the `defconsts` and the `nim-rx-constituents` definition in `(eval-and-compile ...)` forms.

**Comment by reactormonk** [comment]
Should be fixed as by https://github.com/reactormonk/nim-mode/commit/8cb60923236947be25e3a49112e356234861ebdd - thanks for your help @purcell.

**Comment by purcell** [comment]
Happy to help!
